# Generated by Django 5.2.7 on 2025-10-12 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='duration',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('walking', '🚶 Walking'), ('jump_rope', '🤾 Jump Rope'), ('dancing', '💃 Dancing'), ('running', '🏃 Running'), ('cycling', '🚴 Cycling'), ('yoga', '🧘 Yoga'), ('gym', '🏋️ Gym Workout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='calories_burned',
            field=models.PositiveIntegerField(help_text='Calories burned (kcal)'),
        ),
    ]
