# Generated by Django 5.2.7 on 2025-10-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_activitylog_duration_activitylog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('Walking', '🚶 Walking'), ('Jump_rope', '🤾 Jump Rope'), ('Dancing', '💃 Dancing'), ('Running', '🏃 Running'), ('Cycling', '🚴 Cycling'), ('Yoga', '🧘 Yoga'), ('Gym', '🏋️ Gym Workout')], max_length=50),
        ),
    ]
