# Generated by Django 5.2.7 on 2025-10-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='https://i.pravatar.cc/100', null=True),
        ),
    ]
