# Generated by Django 5.2.7 on 2025-10-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='https://i.pinimg.com/474x/f2/b0/38/f2b0386dc82c62330d2133b85950e557.jpg?nii=t', null=True),
        ),
    ]
